### ISSUE TITLE
Copying Functionality Suggestion

### ISSUE THREAD

**Issue by Poly2it** [MisionThi/NBTtooltips#2]
Hello MisionThi! 
I've begun developing a resource pack with custom item textures, and found that your mod to be immensely useful while developing.
I do have one suggestion for the mod, and that is the ability to copy the NBT-data of an item to your clipboard.
My process for creating NBT-reliant textures right now is to copy the NBT by hand character by character.
-PolyBit

**Comment by MisionThi** [comment]
Thank you for the suggestion, I can look into it when I got some more time on my hands again! :D
