### ISSUE TITLE
1.21.1 support?

### ISSUE THREAD

**Issue by minelolpride** [MisionThi/NBTtooltips#20]
Version 0.1.4 on Modrinth is listed to have support for 1.21.x, however will not launch with 1.21.1 as the mod is expecting exactly version 1.21.

**Comment by zndrmn** [comment]
If you ever run into a mod that _should_ work on a certain version, but hard depends on a minecraft version; then you can just do this:

Create a file called `fabric_loader_dependencies.json` and put it into your config folder.
Then add this to the file you just created.
```json
{
	"version": 1,
	  "overrides": {
		"nbttooltips": {
			"-depends": {
				"minecraft": "1.21.1"
			}
		}
	}
}
```

**Comment by minelolpride** [comment]
Thank you, I didn't know I could do that!
